package wf.garnier.spring.security.seven.authorization.server;

import java.util.List;
import java.util.stream.Collectors;

import org.jspecify.annotations.Nullable;

import org.springframework.stereotype.Service;
import static java.util.Map.entry;
import static java.util.Map.ofEntries;

@Service
class HugoAwardsService {

	List<Book> getWinner(@Nullable Integer from, @Nullable Integer to) {
		return WINNERS.stream()
			.filter(b -> from == null || b.yearWon() >= from)
			.filter(b -> to == null || b.yearWon() <= to)
			.collect(Collectors.toList());
	}

	List<Book> getNominees(int year) {
		return NOMINEES.getOrDefault(year, List.of());
	}

	static final List<Book> WINNERS = List.of(new Book("Alfred Bester", "The Demolished Man", 1953),
			new Book("Mark Clifton", "They'd Rather Be Right (also known as The Forever Machine)", 1955),
			new Book("Robert A. Heinlein", "Double Star", 1956), new Book("Fritz Leiber", "The Big Time", 1958),
			new Book("James Blish", "A Case of Conscience", 1959),
			new Book("Robert A. Heinlein", "Starship Troopers", 1960),
			new Book("Walter M. Miller, Jr.", "A Canticle for Leibowitz", 1961),
			new Book("Robert A. Heinlein", "Stranger in a Strange Land", 1962),
			new Book("Philip K. Dick", "The Man in the High Castle", 1963),
			new Book("Clifford D. Simak", "Here Gather the Stars (also known as Way Station)", 1964),
			new Book("Fritz Leiber", "The Wanderer", 1965), new Book("Frank Herbert", "Dune", 1966),
			new Book("Robert A. Heinlein", "The Moon Is a Harsh Mistress", 1967),
			new Book("Roger Zelazny", "Lord of Light", 1968), new Book("John Brunner", "Stand on Zanzibar", 1969),
			new Book("Ursula K. Le Guin", "The Left Hand of Darkness", 1970),
			new Book("Larry Niven", "Ringworld", 1971),
			new Book("Philip José Farmer", "To Your Scattered Bodies Go", 1972),
			new Book("Isaac Asimov", "The Gods Themselves", 1973),
			new Book("Arthur C. Clarke", "Rendezvous with Rama", 1974),
			new Book("Ursula K. Le Guin", "The Dispossessed", 1975), new Book("Joe Haldeman", "The Forever War", 1976),
			new Book("Kate Wilhelm", "Where Late the Sweet Birds Sang", 1977),
			new Book("Frederik Pohl", "Gateway", 1978), new Book("Vonda N. McIntyre", "Dreamsnake", 1979),
			new Book("Arthur C. Clarke", "The Fountains of Paradise", 1980),
			new Book("Joan D. Vinge", "The Snow Queen", 1981), new Book("C. J. Cherryh", "Downbelow Station", 1982),
			new Book("Isaac Asimov", "Foundation's Edge", 1983), new Book("David Brin", "Startide Rising", 1984),
			new Book("William Gibson", "Neuromancer", 1985), new Book("Orson Scott Card", "Ender's Game", 1986),
			new Book("Orson Scott Card", "Speaker for the Dead", 1987), new Book("David Brin", "The Uplift War", 1988),
			new Book("C. J. Cherryh", "Cyteen", 1989), new Book("Dan Simmons", "Hyperion", 1990),
			new Book("Lois McMaster Bujold", "The Vor Game", 1991), new Book("Lois McMaster Bujold", "Barrayar", 1992),
			new Book("Vernor Vinge", "A Fire Upon the Deep", 1993),
			new Book("Kim Stanley Robinson", "Green Mars", 1994),
			new Book("Lois McMaster Bujold", "Mirror Dance", 1995),
			new Book("Neal Stephenson", "The Diamond Age", 1996), new Book("Kim Stanley Robinson", "Blue Mars", 1997),
			new Book("Joe Haldeman", "Forever Peace", 1998),
			new Book("Connie Willis", "To Say Nothing of the Dog", 1999),
			new Book("Vernor Vinge", "A Deepness in the Sky", 2000),
			new Book("J. K. Rowling", "Harry Potter and the Goblet of Fire", 2001),
			new Book("Neil Gaiman", "American Gods", 2002), new Book("Robert J. Sawyer", "Hominids", 2003),
			new Book("Lois McMaster Bujold", "Paladin of Souls", 2004),
			new Book("Susanna Clarke", "Jonathan Strange & Mr Norrell", 2005),
			new Book("Robert Charles Wilson", "Spin", 2006), new Book("Vernor Vinge", "Rainbows End", 2007),
			new Book("Michael Chabon", "The Yiddish Policemen's Union", 2008),
			new Book("Neil Gaiman", "The Graveyard Book", 2009), new Book("Paolo Bacigalupi", "The Windup Girl", 2010),
			new Book("Connie Willis", "Blackout/All Clear", 2011), new Book("Jo Walton", "Among Others", 2012),
			new Book("John Scalzi", "Redshirts", 2013), new Book("Ann Leckie", "Ancillary Justice", 2014),
			new Book("Cixin Liu (Chinese)", "The Three-Body Problem", 2015),
			new Book("N. K. Jemisin", "The Fifth Season", 2016), new Book("N. K. Jemisin", "The Obelisk Gate", 2017),
			new Book("N. K. Jemisin", "The Stone Sky", 2018),
			new Book("Mary Robinette Kowal", "The Calculating Stars", 2019),
			new Book("Arkady Martine", "A Memory Called Empire", 2020),
			new Book("Martha Wells", "Network Effect", 2021),
			new Book("Arkady Martine", "A Desolation Called Peace", 2022),
			new Book("Ursula Vernon (as T. Kingfisher)", "Nettle & Bone", 2023),
			new Book("Emily Tesh", "Some Desperate Glory", 2024),
			new Book("Robert Jackson Bennett", "The Tainted Cup", 2025));

	static final java.util.Map<Integer, List<Book>> NOMINEES = ofEntries(
			entry(1953, List.of(new Book("Alfred Bester", "The Demolished Man", 1953))),
			entry(1955,
					List.of(new Book("Mark Clifton", "They'd Rather Be Right (also known as The Forever Machine)",
							1955))),
			entry(1956,
					List.of(new Book("Robert A. Heinlein", "Double Star", 1956),
							new Book("Eric Frank Russell", "Call Him Dead (also known as Three to Conquer)", 1956),
							new Book("Isaac Asimov", "The End of Eternity", 1956),
							new Book("Cyril M. Kornbluth", "Not This August", 1956),
							new Book("Leigh Brackett", "The Long Tomorrow", 1956))),
			entry(1958, List.of(new Book("Fritz Leiber", "The Big Time", 1958))),
			entry(1959,
					List.of(new Book("James Blish", "A Case of Conscience", 1959),
							new Book("Poul Anderson", "We Have Fed Our Sea (also known as The Enemy Stars)", 1959),
							new Book("Algis Budrys", "Who?", 1959),
							new Book("Robert A. Heinlein", "Have Space Suit — Will Travel", 1959),
							new Book("Robert Sheckley", "Time Killer (also known as Immortality, Inc.)", 1959))),
			entry(1960,
					List.of(new Book("Robert A. Heinlein", "Starship Troopers", 1960),
							new Book("Gordon R. Dickson", "Dorsai! (also known as The Genetic General)", 1960),
							new Book("Murray Leinster", "The Pirates of Ersatz (also known as The Pirates of Zan)",
									1960),
							new Book("Mark Phillips", "That Sweet Little Old Lady (also known as Brain Twister)", 1960),
							new Book("Kurt Vonnegut", "The Sirens of Titan", 1960))),
			entry(1961, List.of(new Book("Walter M. Miller, Jr.", "A Canticle for Leibowitz", 1961),
					new Book("Poul Anderson", "The High Crusade", 1961), new Book("Algis Budrys", "Rogue Moon", 1961),
					new Book("Harry Harrison", "Deathworld", 1961),
					new Book("Theodore Sturgeon", "Venus Plus X", 1961))),
			entry(1962, List.of(new Book("Robert A. Heinlein", "Stranger in a Strange Land", 1962),
					new Book("Daniel F. Galouye", "Dark Universe", 1962),
					new Book("Harry Harrison", "Planet of the Damned (also known as Sense of Obligation)", 1962),
					new Book("Clifford D. Simak", "The Fisherman (also known as Time Is the Simplest Thing)", 1962),
					new Book("James White", "Second Ending", 1962))),
			entry(1963, List.of(new Book("Philip K. Dick", "The Man in the High Castle", 1963),
					new Book("Marion Zimmer Bradley", "The Sword of Aldones", 1963),
					new Book("Arthur C. Clarke", "A Fall of Moondust", 1963),
					new Book("H. Beam Piper", "Little Fuzzy", 1963), new Book("Jean Bruller (French)", "Sylva", 1963))),
			entry(1964, List.of(
					new Book("Clifford D. Simak", "Here Gather the Stars (also known as Way Station)", 1964),
					new Book("Robert A. Heinlein", "Glory Road", 1964), new Book("Andre Norton", "Witch World", 1964),
					new Book("Frank Herbert", "Dune World", 1964), new Book("Kurt Vonnegut", "Cat's Cradle", 1964))),
			entry(1965,
					List.of(new Book("Fritz Leiber", "The Wanderer", 1965),
							new Book("John Brunner", "The Whole Man", 1965), new Book("Edgar Pangborn", "Davy", 1965),
							new Book("Cordwainer Smith",
									"The Planet Buyer (also known as The Boy Who Bought Old Earth)", 1965))),
			entry(1966,
					List.of(new Book("Frank Herbert", "Dune", 1966),
							new Book("Roger Zelazny", "...And Call Me Conrad (also known as This Immortal)", 1966),
							new Book("John Brunner", "The Squares of the City", 1966),
							new Book("Robert A. Heinlein", "The Moon Is a Harsh Mistress", 1966),
							new Book("Edward E. Smith", "Skylark DuQuesne", 1966))),
			entry(1967,
					List.of(new Book("Robert A. Heinlein", "The Moon Is a Harsh Mistress", 1967),
							new Book("Samuel R. Delany", "Babel-17", 1967),
							new Book("Randall Garrett", "Too Many Magicians", 1967),
							new Book("Daniel Keyes", "Flowers for Algernon", 1967),
							new Book("James H. Schmitz", "The Witches of Karres", 1967),
							new Book("Thomas Burnett Swann", "Day of the Minotaur", 1967))),
			entry(1968, List.of(new Book("Roger Zelazny", "Lord of Light", 1968),
					new Book("Samuel R. Delany", "The Einstein Intersection", 1968),
					new Book("Piers Anthony", "Chthon", 1968), new Book("Chester Anderson", "The Butterfly Kid", 1968),
					new Book("Robert Silverberg", "Thorns", 1968))),
			entry(1969,
					List.of(new Book("John Brunner", "Stand on Zanzibar", 1969),
							new Book("Alexei Panshin", "Rite of Passage", 1969),
							new Book("Samuel R. Delany", "Nova", 1969), new Book("R. A. Lafferty", "Past Master", 1969),
							new Book("Clifford D. Simak", "The Goblin Reservation", 1969))),
			entry(1970, List.of(new Book("Ursula K. Le Guin", "The Left Hand of Darkness", 1970),
					new Book("Robert Silverberg", "Up the Line", 1970), new Book("Piers Anthony", "Macroscope", 1970),
					new Book("Kurt Vonnegut", "Slaughterhouse-Five", 1970),
					new Book("Norman Spinrad", "Bug Jack Barron", 1970))),
			entry(1971,
					List.of(new Book("Larry Niven", "Ringworld", 1971), new Book("Poul Anderson", "Tau Zero", 1971),
							new Book("Robert Silverberg", "Tower of Glass", 1971),
							new Book("Wilson Tucker", "The Year of the Quiet Sun", 1971),
							new Book("Hal Clement", "Star Light", 1971))),
			entry(1972, List.of(new Book("Philip José Farmer", "To Your Scattered Bodies Go", 1972),
					new Book("Ursula K. Le Guin", "The Lathe of Heaven", 1972),
					new Book("Anne McCaffrey", "Dragonquest", 1972), new Book("Roger Zelazny", "Jack of Shadows", 1972),
					new Book("Robert Silverberg", "A Time of Changes", 1972))),
			entry(1973,
					List.of(new Book("Isaac Asimov", "The Gods Themselves", 1973),
							new Book("David Gerrold", "When HARLIE Was One", 1973),
							new Book("Poul Anderson", "There Will Be Time", 1973),
							new Book("Robert Silverberg", "The Book of Skulls", 1973),
							new Book("Robert Silverberg", "Dying Inside", 1973),
							new Book("Clifford D. Simak", "A Choice of Gods", 1973))),
			entry(1974,
					List.of(new Book("Arthur C. Clarke", "Rendezvous with Rama", 1974),
							new Book("Robert A. Heinlein", "Time Enough for Love", 1974),
							new Book("Larry Niven", "Protector", 1974),
							new Book("Poul Anderson", "The People of the Wind", 1974),
							new Book("David Gerrold", "The Man Who Folded Himself", 1974))),
			entry(1975,
					List.of(new Book("Ursula K. Le Guin", "The Dispossessed", 1975),
							new Book("Poul Anderson", "Fire Time", 1975),
							new Book("Philip K. Dick", "Flow My Tears, the Policeman Said", 1975),
							new Book("Larry Niven", "The Mote in God's Eye", 1975),
							new Book("Christopher Priest", "Inverted World", 1975))),
			entry(1976, List.of(new Book("Joe Haldeman", "The Forever War", 1976),
					new Book("Roger Zelazny", "Doorways in the Sand", 1976), new Book("Larry Niven", "Inferno", 1976),
					new Book("Alfred Bester", "The Computer Connection (also known as The Indian Giver)", 1976),
					new Book("Robert Silverberg", "The Stochastic Man", 1976))),
			entry(1977, List.of(new Book("Kate Wilhelm", "Where Late the Sweet Birds Sang", 1977),
					new Book("Joe Haldeman", "Mindbridge", 1977), new Book("Frank Herbert", "Children of Dune", 1977),
					new Book("Frederik Pohl", "Man Plus", 1977),
					new Book("Robert Silverberg", "Shadrach in the Furnace", 1977))),
			entry(1978,
					List.of(new Book("Frederik Pohl", "Gateway", 1978),
							new Book("Marion Zimmer Bradley", "The Forbidden Tower", 1978),
							new Book("Larry Niven", "Lucifer's Hammer", 1978),
							new Book("Gordon R. Dickson", "Time Storm", 1978),
							new Book("George R. R. Martin", "Dying of the Light", 1978))),
			entry(1979,
					List.of(new Book("Vonda N. McIntyre", "Dreamsnake", 1979),
							new Book("Anne McCaffrey", "The White Dragon", 1979),
							new Book("C. J. Cherryh", "The Faded Sun: Kesrith", 1979),
							new Book("Tom Reamy", "Blind Voices", 1979))),
			entry(1980,
					List.of(new Book("Arthur C. Clarke", "The Fountains of Paradise", 1980),
							new Book("John Varley", "Titan", 1980), new Book("Frederik Pohl", "Jem", 1980),
							new Book("Patricia A. McKillip", "Harpist in the Wind", 1980),
							new Book("Thomas M. Disch", "On Wings of Song", 1980))),
			entry(1981,
					List.of(new Book("Joan D. Vinge", "The Snow Queen", 1981),
							new Book("Robert Silverberg", "Lord Valentine's Castle", 1981),
							new Book("Larry Niven", "The Ringworld Engineers", 1981),
							new Book("Frederik Pohl", "Beyond the Blue Event Horizon", 1981),
							new Book("John Varley", "Wizard", 1981))),
			entry(1982,
					List.of(new Book("C. J. Cherryh", "Downbelow Station", 1982),
							new Book("Gene Wolfe", "The Claw of the Conciliator", 1982),
							new Book("Julian May", "The Many-Colored Land", 1982),
							new Book("Clifford D. Simak", "Project Pope", 1982),
							new Book("John Crowley", "Little, Big", 1982))),
			entry(1983,
					List.of(new Book("Isaac Asimov", "Foundation's Edge", 1983),
							new Book("C. J. Cherryh", "The Pride of Chanur", 1983),
							new Book("Arthur C. Clarke", "2010: Odyssey Two", 1983),
							new Book("Robert A. Heinlein", "Friday", 1983),
							new Book("Donald Kingsbury", "Courtship Rite", 1983),
							new Book("Gene Wolfe", "The Sword of the Lictor", 1983))),
			entry(1984,
					List.of(new Book("David Brin", "Startide Rising", 1984),
							new Book("R. A. MacAvoy", "Tea with the Black Dragon", 1984),
							new Book("John Varley", "Millennium", 1984),
							new Book("Anne McCaffrey", "Moreta: Dragonlady of Pern", 1984),
							new Book("Isaac Asimov", "The Robots of Dawn", 1984))),
			entry(1985, List.of(new Book("William Gibson", "Neuromancer", 1985),
					new Book("David R. Palmer", "Emergence", 1985), new Book("Vernor Vinge", "The Peace War", 1985),
					new Book("Robert A. Heinlein", "Job: A Comedy of Justice", 1985),
					new Book("Larry Niven", "The Integral Trees", 1985))),
			entry(1986, List.of(new Book("Orson Scott Card", "Ender's Game", 1986),
					new Book("C. J. Cherryh", "Cuckoo's Egg", 1986), new Book("David Brin", "The Postman", 1986),
					new Book("Larry Niven", "Footfall", 1986), new Book("Greg Bear", "Blood Music", 1986))),
			entry(1987, List.of(new Book("Orson Scott Card", "Speaker for the Dead", 1987),
					new Book("Bob Shaw", "The Ragged Astronauts", 1987), new Book("William Gibson", "Count Zero", 1987),
					new Book("Vernor Vinge", "Marooned in Realtime", 1987),
					new Book("L. Ron Hubbard", "Black Genesis", 1987))),
			entry(1988, List.of(new Book("David Brin", "The Uplift War", 1988),
					new Book("George Alec Effinger", "When Gravity Fails", 1988),
					new Book("Orson Scott Card", "Seventh Son", 1988), new Book("Greg Bear", "The Forge of God", 1988),
					new Book("Gene Wolfe", "The Urth of the New Sun", 1988))),
			entry(1989,
					List.of(new Book("C. J. Cherryh", "Cyteen", 1989),
							new Book("Orson Scott Card", "Red Prophet", 1989),
							new Book("Lois McMaster Bujold", "Falling Free", 1989),
							new Book("Bruce Sterling", "Islands in the Net", 1989),
							new Book("William Gibson", "Mona Lisa Overdrive", 1989))),
			entry(1990,
					List.of(new Book("Dan Simmons", "Hyperion", 1990),
							new Book("George Alec Effinger", "A Fire in the Sun", 1990),
							new Book("Orson Scott Card", "Prentice Alvin", 1990),
							new Book("Poul Anderson", "The Boat of a Million Years", 1990),
							new Book("Sheri S. Tepper", "Grass", 1990))),
			entry(1991, List.of(new Book("Lois McMaster Bujold", "The Vor Game", 1991),
					new Book("David Brin", "Earth", 1991), new Book("Dan Simmons", "The Fall of Hyperion", 1991),
					new Book("Michael P. Kube-McDowell", "The Quiet Pools", 1991),
					new Book("Greg Bear", "Queen of Angels", 1991))),
			entry(1992, List.of(new Book("Lois McMaster Bujold", "Barrayar", 1992),
					new Book("Emma Bull", "Bone Dance", 1992),
					new Book("Anne McCaffrey", "All the Weyrs of Pern", 1992),
					new Book("Joan D. Vinge", "The Summer Queen", 1992), new Book("Orson Scott Card", "Xenocide", 1992),
					new Book("Michael Swanwick", "Stations of the Tide", 1992))),
			entry(1993,
					List.of(new Book("Vernor Vinge", "A Fire Upon the Deep", 1993),
							new Book("Connie Willis", "Doomsday Book", 1993),
							new Book("Kim Stanley Robinson", "Red Mars", 1993),
							new Book("Maureen F. McHugh", "China Mountain Zhang", 1993),
							new Book("John Varley", "Steel Beach", 1993))),
			entry(1994, List.of(new Book("Kim Stanley Robinson", "Green Mars", 1994),
					new Book("Greg Bear", "Moving Mars", 1994), new Book("Nancy Kress", "Beggars in Spain", 1994),
					new Book("David Brin", "Glory Season", 1994), new Book("William Gibson", "Virtual Light", 1994))),
			entry(1995,
					List.of(new Book("Lois McMaster Bujold", "Mirror Dance", 1995),
							new Book("John Barnes", "Mother of Storms", 1995),
							new Book("Nancy Kress", "Beggars and Choosers", 1995),
							new Book("Michael Bishop", "Brittle Innings", 1995),
							new Book("James K. Morrow", "Towing Jehovah", 1995))),
			entry(1996,
					List.of(new Book("Neal Stephenson", "The Diamond Age", 1996),
							new Book("Stephen Baxter", "The Time Ships", 1996),
							new Book("David Brin", "Brightness Reef", 1996),
							new Book("Robert J. Sawyer", "The Terminal Experiment (also known as Hobson's Choice)",
									1996),
							new Book("Connie Willis", "Remake", 1996))),
			entry(1997, List.of(new Book("Kim Stanley Robinson", "Blue Mars", 1997),
					new Book("Lois McMaster Bujold", "Memory", 1997),
					new Book("Elizabeth Moon", "Remnant Population", 1997),
					new Book("Robert J. Sawyer", "Starplex", 1997), new Book("Bruce Sterling", "Holy Fire", 1997))),
			entry(1998,
					List.of(new Book("Joe Haldeman", "Forever Peace", 1998),
							new Book("Walter Jon Williams", "City on Fire", 1998),
							new Book("Dan Simmons", "The Rise of Endymion", 1998),
							new Book("Robert J. Sawyer", "Frameshift", 1998),
							new Book("Michael Swanwick", "Jack Faust", 1998))),
			entry(1999,
					List.of(new Book("Connie Willis", "To Say Nothing of the Dog", 1999),
							new Book("Mary Doria Russell", "Children of God", 1999),
							new Book("Robert Charles Wilson", "Darwinia", 1999),
							new Book("Bruce Sterling", "Distraction", 1999),
							new Book("Robert J. Sawyer", "Factoring Humanity", 1999))),
			entry(2000, List.of(new Book("Vernor Vinge", "A Deepness in the Sky", 2000),
					new Book("Lois McMaster Bujold", "A Civil Campaign", 2000),
					new Book("Neal Stephenson", "Cryptonomicon", 2000), new Book("Greg Bear", "Darwin's Radio", 2000),
					new Book("J. K. Rowling", "Harry Potter and the Prisoner of Azkaban", 2000))),
			entry(2001,
					List.of(new Book("J. K. Rowling", "Harry Potter and the Goblet of Fire", 2001),
							new Book("George R. R. Martin", "A Storm of Swords", 2001),
							new Book("Robert J. Sawyer", "Calculating God", 2001),
							new Book("Ken MacLeod", "The Sky Road", 2001),
							new Book("Nalo Hopkinson", "Midnight Robber", 2001))),
			entry(2002,
					List.of(new Book("Neil Gaiman", "American Gods", 2002),
							new Book("Lois McMaster Bujold", "The Curse of Chalion", 2002),
							new Book("Connie Willis", "Passage", 2002),
							new Book("China Miéville", "Perdido Street Station", 2002),
							new Book("Robert Charles Wilson", "The Chronoliths", 2002),
							new Book("Ken MacLeod", "Cosmonaut Keep", 2002))),
			entry(2003,
					List.of(new Book("Robert J. Sawyer", "Hominids", 2003),
							new Book("David Brin", "Kiln People (UK: Kil'n People)", 2003),
							new Book("Michael Swanwick", "Bones of the Earth", 2003),
							new Book("China Miéville", "The Scar", 2003),
							new Book("Kim Stanley Robinson", "The Years of Rice and Salt", 2003))),
			entry(2004,
					List.of(new Book("Lois McMaster Bujold", "Paladin of Souls", 2004),
							new Book("Dan Simmons", "Ilium", 2004), new Book("Charles Stross", "Singularity Sky", 2004),
							new Book("Robert Charles Wilson", "Blind Lake", 2004),
							new Book("Robert J. Sawyer", "Humans", 2004))),
			entry(2005, List.of(new Book("Susanna Clarke", "Jonathan Strange & Mr Norrell", 2005),
					new Book("Ian McDonald", "River of Gods", 2005), new Book("Iain M. Banks", "The Algebraist", 2005),
					new Book("Charles Stross", "Iron Sunrise", 2005),
					new Book("China Miéville", "Iron Council", 2005))),
			entry(2006, List.of(new Book("Robert Charles Wilson", "Spin", 2006),
					new Book("Ken MacLeod", "Learning the World", 2006),
					new Book("George R. R. Martin", "A Feast for Crows", 2006),
					new Book("John Scalzi", "Old Man's War", 2006), new Book("Charles Stross", "Accelerando", 2006))),
			entry(2007, List.of(new Book("Vernor Vinge", "Rainbows End", 2007),
					new Book("Charles Stross", "Glasshouse", 2007),
					new Book("Naomi Novik", "His Majesty's Dragon", 2007),
					new Book("Michael F. Flynn", "Eifelheim", 2007), new Book("Peter Watts", "Blindsight", 2007))),
			entry(2008, List.of(new Book("Michael Chabon", "The Yiddish Policemen's Union", 2008),
					new Book("John Scalzi", "The Last Colony", 2008), new Book("Charles Stross", "Halting State", 2008),
					new Book("Robert J. Sawyer", "Rollback", 2008), new Book("Ian McDonald", "Brasyl", 2008))),
			entry(2009, List.of(new Book("Neil Gaiman", "The Graveyard Book", 2009),
					new Book("Cory Doctorow", "Little Brother", 2009), new Book("Neal Stephenson", "Anathem", 2009),
					new Book("Charles Stross", "Saturn's Children", 2009),
					new Book("John Scalzi", "Zoe's Tale", 2009))),
			entry(2010,
					List.of(new Book("Paolo Bacigalupi", "The Windup Girl", 2010),
							new Book("China Miéville", "The City & the City", 2010),
							new Book("Cherie Priest", "Boneshaker", 2010), new Book("Robert J. Sawyer", "Wake", 2010),
							new Book("Catherynne M. Valente", "Palimpsest", 2010),
							new Book("Robert Charles Wilson", "Julian Comstock: A Story of 22nd-Century America",
									2010))),
			entry(2011,
					List.of(new Book("Connie Willis", "Blackout/All Clear", 2011),
							new Book("Lois McMaster Bujold", "Cryoburn", 2011),
							new Book("Ian McDonald", "The Dervish House", 2011), new Book("Mira Grant", "Feed", 2011),
							new Book("N. K. Jemisin", "The Hundred Thousand Kingdoms", 2011))),
			entry(2012,
					List.of(new Book("Jo Walton", "Among Others", 2012),
							new Book("George R. R. Martin", "A Dance with Dragons", 2012),
							new Book("Mira Grant", "Deadline", 2012), new Book("China Miéville", "Embassytown", 2012),
							new Book("James S. A. Corey", "Leviathan Wakes", 2012))),
			entry(2013,
					List.of(new Book("John Scalzi", "Redshirts", 2013), new Book("Kim Stanley Robinson", "2312", 2013),
							new Book("Mira Grant", "Blackout", 2013),
							new Book("Lois McMaster Bujold", "Captain Vorpatril's Alliance", 2013),
							new Book("Saladin Ahmed", "Throne of the Crescent Moon", 2013))),
			entry(2014, List.of(new Book("Ann Leckie", "Ancillary Justice", 2014),
					new Book("Charles Stross", "Neptune's Brood", 2014), new Book("Mira Grant", "Parasite", 2014),
					new Book("Larry Correia", "Warbound", 2014), new Book("Robert Jordan", "The Wheel of Time", 2014))),
			entry(2015, List.of(new Book("Cixin Liu (Chinese)", "The Three-Body Problem", 2015),
					new Book("Katherine Addison", "The Goblin Emperor", 2015),
					new Book("Kevin J. Anderson", "The Dark Between the Stars", 2015),
					new Book("Jim Butcher", "Skin Game", 2015), new Book("Ann Leckie", "Ancillary Sword", 2015))),
			entry(2016,
					List.of(new Book("N. K. Jemisin", "The Fifth Season", 2016),
							new Book("Naomi Novik", "Uprooted", 2016), new Book("Ann Leckie", "Ancillary Mercy", 2016),
							new Book("Neal Stephenson", "Seveneves", 2016),
							new Book("Jim Butcher", "The Cinder Spires: The Aeronaut's Windlass", 2016))),
			entry(2017,
					List.of(new Book("N. K. Jemisin", "The Obelisk Gate", 2017),
							new Book("Charlie Jane Anders", "All the Birds in the Sky", 2017),
							new Book("Becky Chambers", "A Closed and Common Orbit", 2017),
							new Book("Cixin Liu (Chinese)", "Death's End", 2017),
							new Book("Yoon Ha Lee", "Ninefox Gambit", 2017),
							new Book("Ada Palmer", "Too Like the Lightning", 2017))),
			entry(2018, List.of(new Book("N. K. Jemisin", "The Stone Sky", 2018),
					new Book("John Scalzi", "The Collapsing Empire", 2018),
					new Book("Kim Stanley Robinson", "New York 2140", 2018), new Book("Ann Leckie", "Provenance", 2018),
					new Book("Yoon Ha Lee", "Raven Stratagem", 2018), new Book("Mur Lafferty", "Six Wakes", 2018))),
			entry(2019, List.of(new Book("Mary Robinette Kowal", "The Calculating Stars", 2019),
					new Book("Becky Chambers", "Record of a Spaceborn Few", 2019),
					new Book("Yoon Ha Lee", "Revenant Gun", 2019), new Book("Naomi Novik", "Spinning Silver", 2019),
					new Book("Rebecca Roanhorse", "Trail of Lightning", 2019),
					new Book("Catherynne M. Valente", "Space Opera", 2019))),
			entry(2020,
					List.of(new Book("Arkady Martine", "A Memory Called Empire", 2020),
							new Book("Charlie Jane Anders", "The City in the Middle of the Night", 2020),
							new Book("Tamsyn Muir", "Gideon the Ninth", 2020),
							new Book("Kameron Hurley", "The Light Brigade", 2020),
							new Book("Seanan McGuire", "Middlegame", 2020),
							new Book("Alix E. Harrow", "The Ten Thousand Doors of January", 2020))),
			entry(2021, List.of(new Book("Martha Wells", "Network Effect", 2021),
					new Book("Rebecca Roanhorse", "Black Sun", 2021),
					new Book("N. K. Jemisin", "The City We Became", 2021),
					new Book("Tamsyn Muir", "Harrow the Ninth", 2021), new Book("Susanna Clarke", "Piranesi", 2021),
					new Book("Mary Robinette Kowal", "The Relentless Moon", 2021))),
			entry(2022,
					List.of(new Book("Arkady Martine", "A Desolation Called Peace", 2022),
							new Book("Becky Chambers", "The Galaxy, and the Ground Within", 2022),
							new Book("Ryka Aoki", "Light From Uncommon Stars", 2022),
							new Book("P. Djèlí Clark", "A Master of Djinn", 2022),
							new Book("Andy Weir", "Project Hail Mary", 2022),
							new Book("Shelley Parker-Chan", "She Who Became the Sun", 2022))),
			entry(2023,
					List.of(new Book("Ursula Vernon (as T. Kingfisher)", "Nettle & Bone", 2023),
							new Book("John Scalzi", "The Kaiju Preservation Society", 2023),
							new Book("Travis Baldree", "Legends & Lattes", 2023),
							new Book("Tamsyn Muir", "Nona the Ninth", 2023),
							new Book("Silvia Moreno-Garcia", "The Daughter of Doctor Moreau", 2023),
							new Book("Mary Robinette Kowal", "The Spare Man", 2023))),
			entry(2024, List.of(new Book("Emily Tesh", "Some Desperate Glory", 2024),
					new Book("Shannon Chakraborty", "The Adventures of Amina al-Sirafi", 2024),
					new Book("Vajra Chandrasekera", "The Saint of Bright Doors", 2024),
					new Book("John Scalzi", "Starter Villain", 2024), new Book("Ann Leckie", "Translation State", 2024),
					new Book("Martha Wells", "Witch King", 2024))),
			entry(2025, List.of(new Book("Robert Jackson Bennett", "The Tainted Cup", 2025),
					new Book("Adrian Tchaikovsky", "Alien Clay", 2025),
					new Book("Kaliane Bradley", "The Ministry of Time", 2025),
					new Book("Adrian Tchaikovsky", "Service Model", 2025),
					new Book("John Wiswell", "Someone You Can Build a Nest In", 2025),
					new Book("Ursula Vernon (as T. Kingfisher)", "A Sorceress Comes to Call", 2025),
					new Book("Year", "Year awarded", 2025), new Book("Edgar Rice Burroughs", "Carson of Venus", 2025),
					new Book("E. E. Smith", "Galactic Patrol", 2025),
					new Book("Jack Williamson", "The Legion of Time", 2025),
					new Book("C. S. Lewis", "Out of the Silent Planet", 2025),
					new Book("E. E. Smith", "Gray Lensman", 2025), new Book("T. H. White", "The Ill-Made Knight", 2025),
					new Book("Karin Boye", "Kallocain", 2025),
					new Book("Jack Williamson", "The Reign of Wizardry", 2025),
					new Book("Olaf Stapledon", "Darkness and the Light", 2025),
					new Book("Curt Siodmak", "Donovan's Brain", 2025),
					new Book("Austin Tappan Wright", "Islandia", 2025),
					new Book("E. E. Smith", "Second Stage Lensmen", 2025),
					new Book("Dorothy Macardle", "The Uninvited", 2025),
					new Book("C. L. Moore", "Earth's Last Citadel", 2025),
					new Book("Fritz Leiber", "Gather, Darkness!", 2025),
					new Book("Hermann Hesse", "Das Glasperlenspiel (The Glass Bead Game)", 2025),
					new Book("C. S. Lewis", "Perelandra", 2025), new Book("A. E. van Vogt", "The Weapon Makers", 2025),
					new Book("Robert Graves", "The Golden Fleece", 2025),
					new Book("Edgar Rice Burroughs", "Land of Terror", 2025),
					new Book("Olaf Stapledon", "Sirius: A Fantasy of Love and Discord", 2025),
					new Book("Eric Linklater", "The Wind on the Moon", 2025),
					new Book("A. E. van Vogt", "\"The Winged Man\"", 2025),
					new Book("A. E. van Vogt", "The World of Null-A", 2025),
					new Book("C. S. Lewis", "That Hideous Strength (also known as The Tortured Planet)", 2025),
					new Book("Fritz Leiber", "Destiny Times Three", 2025),
					new Book("Edmond Hamilton (as Brett Sterling)", "Red Sun of Danger (also known as Danger Planet)",
							2025),
					new Book("Isaac Asimov", "Pebble in the Sky", 2025),
					new Book("C. S. Lewis", "The Lion, the Witch and the Wardrobe", 2025),
					new Book("E. E. Smith", "First Lensman", 2025), new Book("Jack Vance", "The Dying Earth", 2025),
					new Book("Arthur C. Clarke", "Childhood's End", 2025),
					new Book("Hal Clement", "Mission of Gravity", 2025),
					new Book("Isaac Asimov", "The Caves of Steel", 2025),
					new Book("Theodore Sturgeon", "More Than Human", 2025))));

}
