spring:
  application:
    name: authorization-server
  security:
    user:
      name: daniel-sso
      password: pw
    oauth2:
      authorizationserver:
        client:
          example-client:
            token:
              access-token-time-to-live: 1h
            registration:
              client-id: "default-client"
              client-secret: "{noop}default-secret"
              client-authentication-methods:
                - "client_secret_basic"
                - "client_secret_post"
                - "none"
              authorization-grant-types:
                - "authorization_code"
                - "client_credentials"
              scopes:
                - openid
                - profile
                - client.create
              redirect-uris:
                - "http://127.0.0.1:8080/authorize/oauth2/code/authserver"
                - "http://127.0.0.1:8080/login/oauth2/code/authserver"
                - "http://localhost:8080/authorize/oauth2/code/authserver"
                - "http://localhost:8080/login/oauth2/code/authserver"
                - "http://localhost:8080/authorize/oauth2/code/default-client"
                - "http://localhost:8080/authorize/oauth2/code/default-client"
server:
  port: 9000
  servlet:
    session:
      cookie:
        name: AUTHORIZATION_SERVER_SESSION_ID
logging:
  level:
    org.springframework.security: TRACE